blog/urls.py
from django.urls import path
from . import views
app_name = 'blog'

urlpatterns = [
    path('', views.index, name='blog_index'),  # name='blog_index' 这是反向查询名 打开网页就是127.0.0.1:8000/blog/
    path('<int:blog_id>/', views.detail, name='blog_detail'), # 打开网页点击了条目1 就是127.0.0.1:8000/blog/1
    path('<int:category_id>/category/', views.category, name='blog_category'),
    path('<int:tag_id>/tag/', views.tag, name='blog_tag'),
    path('search/', views.search, name='blog_search'),
    path('<int:year>/<int:month>/archives/', views.archives, name='blog_archives'),
    path('<int:comment_id>/reply/', views.reply, name='comment_reply')
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=128, verbose_name='博客分类')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '博客分类'
        verbose_name_plural = '博客分类'


class Tags(models.Model):
    name = models.CharField(max_length=128, verbose_name='博客标签')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '博客标签'
        verbose_name_plural = '博客标签'


class Entry(models.Model):
    title = models.CharField(max_length=128, verbose_name='文章标题')
    author = models.ForeignKey(User, verbose_name='博客作者',on_delete=models.CASCADE)
    # 此处采用外键
    # User 是这里的 from django.contrib.auth.models import User

    img = models.ImageField(upload_to='blog_images', null=True, blank=True, verbose_name='博客配图')
    # null=True 表示这个字段在数据库中可以为空，可以没有内容
    # blank=True 表示在admin，就是django的admin的后台创建可以为空。
    # null=True，blank=True 配套出现

    body = models.TextField(verbose_name='博客正文')
    abstract = models.TextField(max_length=256, null=True, blank=True, verbose_name='摘要')
    # 有些人不喜欢用摘要，所以要允许他为空
    visiting = models.PositiveIntegerField(default=0, verbose_name='访问量')

    category = models.ManyToManyField('Category', verbose_name='博客分类')
    # 一个分类下有很多博客，同时博客可以属于不同的分类。这就是多对多

    tags = models.ManyToManyField('Tags', verbose_name='博客标签')

    created_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    # auto_now_add=True 自动保存博客创建的时间
    modified_time = models.DateTimeField(auto_now=True, verbose_name='修改时间')

    # auto_now=True 自动把当前时间添加给他

    def __str__(self):
        return self.title

    def get_absolute_url(self):  # 这个方法会自动生成每一篇博客的链接
        return reverse('blog:blog_detail', kwargs={'blog_id': self.id})
        # reverse 会帮我们自动生成url地址
        # 会生成一个id http://127.0.0.1:8000/blog/2  其中的2就是通过self.id获取

    def increase_visiting(self):  # 如何增加浏览量
        self.visiting += 1
        self.save(update_fields=['visiting'])  # 保存到这个字段

    class Meta:
        ordering = ['-created_time']
        verbose_name = '博客'
        verbose_name_plural = '博客'

blog/views.py
from django.shortcuts import render
from . import models
import markdown
import pygments
from django.core.paginator import PageNotAnInteger, EmptyPage, Paginator
from django.db.models import Q  # django内置的给搜索用的！
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django_comments.models import Comment
from django_comments import models as comment_models

def make_paginator(objects, page, num=5):  # 列表(我对谁分页)，查看第几页， 每页显示多少
    paginator = Paginator(objects, num)
    try:
        object_list = paginator.page(page)
    except PageNotAnInteger:  # 如果用户请求的不是整数页
        object_list = paginator.page(1)  # 我就给他第一页
    except EmptyPage:  # 如果页码超过了我的页码
        object_list = paginator.page(paginator.num_pages)
    return object_list, paginator


def pagination_data(paginator, page):  # 直接拷贝的。拿来用
    """
    用于自定义展示分页页码的方法
    :param paginator: Paginator类的对象
    :param page: 当前请求的页码
    :return: 一个包含所有页码和符号的字典
    """
    if paginator.num_pages == 1:
        # 如果无法分页，也就是只有1页不到的内容，则无需显示分页导航条，不用任何分页导航条的数据，因此返回一个空的字典
        return {}
    # 当前页左边连续的页码号，初始值为空
    left = []

    # 当前页右边连续的页码号，初始值为空
    right = []

    # 标示第 1 页页码后是否需要显示省略号
    left_has_more = False

    # 标示最后一页页码前是否需要显示省略号
    right_has_more = False

    # 标示是否需要显示第 1 页的页码号。
    # 因为如果当前页左边的连续页码号中已经含有第 1 页的页码号，此时就无需再显示第 1 页的页码号，
    # 其它情况下第一页的页码是始终需要显示的。
    # 初始值为 False
    first = False

    # 标示是否需要显示最后一页的页码号。
    # 需要此指示变量的理由和上面相同。
    last = False

    # 获得用户当前请求的页码号
    try:
        page_number = int(page)
    except ValueError:
        page_number = 1
    except:
        page_number = 1

    # 获得分页后的总页数
    total_pages = paginator.num_pages

    # 获得整个分页页码列表，比如分了四页，那么就是 [1, 2, 3, 4]
    page_range = paginator.page_range

    if page_number == 1:
        # 如果用户请求的是第一页的数据，那么当前页左边的不需要数据，因此 left=[]（已默认为空）。
        # 此时只要获取当前页右边的连续页码号，
        # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 right = [2, 3]。
        # 注意这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
        right = page_range[page_number:page_number + 4]

        # 如果最右边的页码号比最后一页的页码号减去 1 还要小，
        # 说明最右边的页码号和最后一页的页码号之间还有其它页码，因此需要显示省略号，通过 right_has_more 来指示。
        if right[-1] < total_pages - 1:
            right_has_more = True

        # 如果最右边的页码号比最后一页的页码号小，说明当前页右边的连续页码号中不包含最后一页的页码
        # 所以需要显示最后一页的页码号，通过 last 来指示
        if right[-1] < total_pages:
            last = True

    elif page_number == total_pages:
        # 如果用户请求的是最后一页的数据，那么当前页右边就不需要数据，因此 right=[]（已默认为空），
        # 此时只要获取当前页左边的连续页码号。
        # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 left = [2, 3]
        # 这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
        left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]

        # 如果最左边的页码号比第 2 页页码号还大，
        # 说明最左边的页码号和第 1 页的页码号之间还有其它页码，因此需要显示省略号，通过 left_has_more 来指示。
        if left[0] > 2:
            left_has_more = True

        # 如果最左边的页码号比第 1 页的页码号大，说明当前页左边的连续页码号中不包含第一页的页码，
        # 所以需要显示第一页的页码号，通过 first 来指示
        if left[0] > 1:
            first = True
    else:
        # 用户请求的既不是最后一页，也不是第 1 页，则需要获取当前页左右两边的连续页码号，
        # 这里只获取了当前页码前后连续两个页码，你可以更改这个数字以获取更多页码。
        left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
        right = page_range[page_number:page_number + 2]

        # 是否需要显示最后一页和最后一页前的省略号
        if right[-1] < total_pages - 1:
            right_has_more = True
        if right[-1] < total_pages:
            last = True

        # 是否需要显示第 1 页和第 1 页后的省略号
        if left[0] > 2:
            left_has_more = True
        if left[0] > 1:
            first = True

    data = {
        'left': left,
        'right': right,
        'left_has_more': left_has_more,
        'right_has_more': right_has_more,
        'first': first,
        'last': last,
    }
    return data


def index(request):
    entries = models.Entry.objects.all()
    # 在首页上展示所有的文章
    page = request.GET.get('page', 1)
    entry_list, paginator = make_paginator(entries, page)
    page_data = pagination_data(paginator, page)
    return render(request, 'blog/index.html', locals())


def detail(request, blog_id):
    # entry = models.Entry.objects.get(id=blog_id)
    entry = get_object_or_404(models.Entry, id=blog_id)
    md = markdown.Markdown(extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        'markdown.extensions.toc',
    ])
    entry.body = md.convert(entry.body)
    entry.toc = md.toc  # 制作目录
    entry.increase_visiting()

    comment_list = list()  # 定义一个列表装顶级评论的

    def get_comment_list(comments):
        for comment in comments:
            comment_list.append(comment)   # 把顶级评论加到列表里
            children = comment.child_comment.all()
            # 这一条怎么来的 是django_comments里面的abstract.py里面的一个字段。里面的 related_name='child_comment'
            # parent_comment = models.ForeignKey('self', default=None, null=True, blank=True, related_name='child_comment',on_delete=models.CASCADE)
            if len(children) > 0:     # 表示有子评论
                get_comment_list(children)    # 递归调用子评论

    top_comments = Comment.objects.filter(object_pk=blog_id, parent_comment=None,
                                          content_type__app_label='blog').order_by('-submit_date')

    get_comment_list(top_comments)

    return render(request, 'blog/detail.html', locals())


def category(request, category_id):  #
    # c = models.Category.objects.get(id=category_id)  # 获取分类
    c = get_object_or_404(models.Category, id=category_id)
    entries = models.Entry.objects.filter(category=c)

    page = request.GET.get('page', 1)  # 需要分页
    entry_list, paginator = make_paginator(entries, page)  # 需要分页
    page_data = pagination_data(paginator, page)  # 需要分页

    return render(request, 'blog/index.html', locals())


def tag(request, tag_id):  #
    # t = models.Tags.objects.get(id=tag_id)  # 获取分类
    t = get_object_or_404(models.Tags, id=tag_id)
    if t.name == '全部':
        entries = models.Entry.objects.all()
    else:
        entries = models.Entry.objects.filter(tags=t)

    page = request.GET.get('page', 1)  # 需要分页
    entry_list, paginator = make_paginator(entries, page)  # 需要分页
    page_data = pagination_data(paginator, page)  # 需要分页

    return render(request, 'blog/index.html', locals())


def search(request):
    keyword = request.GET.get('keyword', None)  # base.html
    #           <form class="navbar-form navbar-left" action="{% url 'blog:blog_search' %}" method="get">
    #             <div class="form-group">
    #               <input type="text" class="form-control" placeholder="Search" name="keyword">
    #             </div>
    #             <button type="submit" class="btn btn-default">搜索</button>
    #           </form>
    if not keyword:
        error_msg = '请输入关键字！'
        return render(request, 'blog/index.html', locals())
    else:  # 用Q方法来搜索看看有没有包含关键字
        entries = models.Entry.objects.filter(Q(title__icontains=keyword) |
                                              Q(body__icontains=keyword) |
                                              Q(abstract__icontains=keyword))

    page = request.GET.get('page', 1)  # 需要分页
    entry_list, paginator = make_paginator(entries, page)  # 需要分页
    page_data = pagination_data(paginator, page)  # 需要分页

    return render(request, 'blog/index.html', locals())


def archives(request, year, month):
    entries = models.Entry.objects.filter(created_time__year=year, created_time__month=month)
    page = request.GET.get('page', 1)  # 需要分页
    entry_list, paginator = make_paginator(entries, page)  # 需要分页
    page_data = pagination_data(paginator, page)  # 需要分页

    return render(request, 'blog/index.html', locals())


def permission_denied(request, exception):
    return render(request, 'blog/403.html', locals())


def page_not_found(request, exception):
    return render(request, 'blog/404.html', locals())


def page_error(request):
    return render(request, 'blog/500.html', locals())


def login(request):
    import requests
    import json
    from django.conf import settings
    code = request.GET.get('code', None)
    if code is None:
        return redirect('/')

    access_token_url = 'https://api.weibo.com/oauth2/access_token?client_id=%s&client_secret=%s&grant_type=authorization_code&redirect_uri=http://www.yoursite.com/login&code=%s'\
                        %(settings.CLIENT_ID, settings.APP_SECRET, code)

    ret = requests.post(access_token_url)

    data = ret.text

    data_dict = json.loads(data)

    token = data_dict['access_token']
    uid = data_dict['uid']

    request.session['token'] = token
    request.session['uid'] = uid
    request.session['login'] = True

    user_info_url = 'https://api.weibo.com/2/users/show.json?access_token=%s&uid=%s' % (token, uid)
    user_info = requests.get(user_info_url)

    user_info_dict = json.loads(user_info.text)

    request.session['screen_name'] = user_info_dict['screen_name']
    request.session['profile_image_url'] = user_info_dict['profile_image_url']

    return redirect(request.GET.get('next', '/'))


def logout(request):
    # 要先判断用户有没有登陆
    if request.session['login']:
        del request.session['login']
        del request.session['uid']
        del request.session['token']
        del request.session['screen_name']
        del request.session['profile_image_url']
        return redirect(request.GET.get('next', '/'))
    else:
        return redirect('/')

    # request.session.flush()   # 如果用这个方法就会把用户全部的信息删掉。有些人想保留的话就只能一项一项去del




def reply(request, comment_id):
    if not request.session.get('login', None) and not request.user.is_authenticated:
        return redirect('/')
    parent_comment = get_object_or_404(comment_models.Comment, id=comment_id)
    return render(request, 'blog/reply.html', locals())

blog/templates/blog/detail.html
{% extends 'blog/base.html' %}
{% load static %}
{% load comments %}
{% block title %}博客详细页面{% endblock %}
{% block css %}
    <link href="{% static 'blog/css/github.css' %}" rel="stylesheet" />
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-9">
                <h1>{{ entry.title }}</h1>
                <p>
                    <strong>{{ entry.author }}</strong>
                    &nbsp;&nbsp;&nbsp;&nbsp;{{ entry.created_time|date:'Y年m月d日' }}

                    &nbsp;&nbsp;&nbsp;&nbsp;分类：
                    {% for category in entry.category.all %}
                        &nbsp;&nbsp;<a href="{% url 'blog:blog_category' category.id %}">{{ category.name }}</a>
                    {% endfor %}

                    &nbsp;&nbsp;&nbsp;&nbsp;标签：
                    {% for tag in entry.tags.all %}
                        &nbsp;&nbsp;<a href="{% url 'blog:blog_tag' tag.id %}">{{ tag.name }}</a>
                    {% endfor %}

                    &nbsp;&nbsp;&nbsp;&nbsp;浏览量：
                        &nbsp;&nbsp;{{ entry.visiting }}

                </p>
                {% if entry.img %}
                <div><img src="{{ entry.img.url }}" alt="博客配图" width="50%"/></div>
                {% endif %}
                <hr />
                <p>
                    {{ entry.body|safe }}
                </p>

            <div class="row">
                <hr />
                {% get_comment_form for entry as form %}
                {% get_comment_count for entry  as comment_count %}
                <h3>评论总数： {{ comment_count }}</h3>
                <hr />
            </div>

{#            评论表单#}
            {% if request.session.login or request.user.is_authenticated %}
                <div class="row">
                    <form class="form-horizontal" action="{% comment_form_target %}" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="input_title" class="pull-left control-label">评论标题：</label>
                            <div class="col-sm-6">
                                <input class="form-control" name="comment_title" id="input_title" placeholder="请输入标题" required />
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="input_comment" class="pull-left control-label">评论内容:</label>
                            <div class="col-sm-6">
                            <textarea style="resize:none;" class="form-control" rows=6 name="comment" id="input_comment" placeholder="在此输入评论" required></textarea>
                            </div>
                        </div>
                        <span style="display: none;">{{ form.honeypot }}</span>
                        {{ form.content_type }}
                        {{ form.object_pk }}
                        {{ form.timestamp }}
                        {{ form.security_hash }}
                        <input type="hidden" name="next" value="{% url 'blog:blog_detail' entry.id %}" />
                        <input  name="parent_id" type="hidden" value="-1" />
                        <input  name="level" type="hidden" value="0" />

                        <div class="form-group col-sm-7">
                            <div class="pull-left" style="margin-left: 68px;">
                                <button type="reset"  class="btn btn-default"><span class="glyphicon glyphicon-repeat"></span>&nbsp;&nbsp;重置</button>
                            </div>
                            <div class="pull-right" style="margin-right: 12px;">
                                <button type="submit" class="btn btn-success" id="id_submit"><span class="glyphicon glyphicon-send"></span>&nbsp;&nbsp;评论</button>
                            </div>
                        </div>


                    </form>
                </div>
            {% else %}
                <h3>登陆后才可以评论</h3>
            {% endif %}
            <hr />


            {#评论显示区#}
            <div class="row">
            {% for comment in comment_list %}
                <div class="single_comment" style="margin-left: {{ comment.level }}em">
                    <div>
                        {% if comment.user_img %}
                            <img src="{{ comment.user_img }}" alt="user_image" />
                        {% else %}
                            <img src="{% static 'blog/images/admin_image.jpg' %}" />
                        {% endif %}
                    </div>
                    <div class="col-md-11 comment-content" style="margin-bottom: 10px;">
                        <strong>{{ comment.comment_title }}</strong>
                        <div>
                            {% if comment.parent_comment %}
                                        {{ comment.user_name }}{{ request.user }}
                                        <i class="glyphicon glyphicon-share-alt"></i>
                                        {{ comment.parent_comment.user_name }}{{ request.user }}
                            {% else %}
                                    By&nbsp;&nbsp;
                                        {{ comment.user_name }}{{ request.user }}
                                    &nbsp;&nbsp;&nbsp;On&nbsp;&nbsp;
                            {% endif %}
                            <em>{{ comment.submit_date }}</em>
                            {% if request.session.login or request.user.is_authenticated %}
                            &nbsp;&nbsp;&nbsp;<a href="{% url 'blog:comment_reply' comment.id %}">回复</a>
                            {% endif %}
                        </div>
                    <br />
                        <p>{{ comment.comment }}</p>
                    </div>
                </div>
            {% endfor %}


            </div>
            </div>


            <div class="col-md-3">
                {% block toc %}
                    <div class="row">
                        <div class="widget">
                            <h3>博客目录:</h3>
                            {{ entry.toc|safe }}
                        </div>
                    </div>
                    <hr />
                {% endblock %}
            {% include 'blog/right_side_bar.html' %}

            </div>
        </div>
    </div>



{% endblock %}

blog/templates/blog/detail自己的有注释111.html
{% extends 'blog/base.html' %}
{% load static %}
{% load comments %}
{% block title %}博客详细页面{% endblock %}
{% block css %}
    <link href="{% static 'blog/css/github.css' %}" rel="stylesheet"/>
{% endblock %}


{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-9>">
                    <h1>{{ entry.title }}</h1>
                    <p>
                        <strong>{{ entry.author }}</strong>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ entry.created_time|date:'Y年m月d日' }}

                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;分类：
                        {% for category in entry.category.all %}   {# 注意语法 #}
                            <a href="{% url 'blog:blog_category' category.id %}">{{ category.name }}</a>  {# 注意语法  不是category_id #}
                        {% endfor %}
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;标签：
                        {% for tag in entry.tags.all %}   {# 注意语法 #}
                            <a href="{% url 'blog:blog_tag' tag.id %}">{{ tag.name }}</a>
                        {% endfor %}
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;浏览量：{{ entry.visiting }}
                    </p>
                    {% if entry.img %}
                        <div><img src="{{ entry.img.url }}" alt="博客配图" width="50%"/></div>
                    {% endif %}
                    <hr/>
                    <p>
                        {{ entry.body|safe }}
                    </p>
       <div class="row">
                <hr />
                {% get_comment_form for entry as form %}
                {% get_comment_count for entry  as comment_count %}
                <h3>评论总数： {{ comment_count }}</h3>
                <hr />
            </div>

                {#评论表单#}
            {% if request.session.login or request.user.is_authenticated %}
                <div class="row">
                    <form class="form-horizontal" action="{% comment_form_target %}" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="input_title" class="pull-left control-label">评论标题：</label>
                            <div class="col-sm-6">
                                <input class="form-control" name="comment_title" id="input_title" placeholder="请输入标题" required />
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="input_comment" class="pull-left control-label">评论内容:</label>
                            <div class="col-sm-6">
                            <textarea style="resize:none;" class="form-control" rows=6 name="comment" id="input_comment" placeholder="在此输入评论" required></textarea>
                            </div>
                        </div>
                        <span style="display: none;">{{ form.honeypot }}</span>  {# 防止机器人！ #}
                        {{ form.content_type }}
                        {{ form.object_pk }}
                        {{ form.timestamp }}
                        {{ form.security_hash }}
                        <input type="hidden" name="next" value="{% url 'blog:blog_detail' entry.id %}" />  {# 提交评论后会返回原先的页面 #}
                        <input  name="parent_id" type="hidden" value="-1" />   {# value="-1" 表示是一条原发的评论，不是回复别人 #}
                        <input  name="level" type="hidden" value="0" />

                        <div class="form-group col-sm-7">
                            <div class="pull-left" style="margin-left: 68px;">
                                <button type="reset"  class="btn btn-default"><span class="glyphicon glyphicon-repeat"></span>&nbsp;&nbsp;重置</button>
                            </div>
                            <div class="pull-right" style="margin-right: 12px;">
                                <button type="submit" class="btn btn-success" id="id_submit"><span class="glyphicon glyphicon-send"></span>&nbsp;&nbsp;评论</button>
                            </div>
                        </div>
                    </form>
                </div>
            {% else %}
                <h3>登陆后才可以评论</h3>
            {% endif %}
            <hr />


                {# 评论显示区#}
            <div class="row">
            {% for comment in comment_list %}
                <div class="single_comment" style="margin-left: {{ comment.level }}em">  {# 根据我comment.level来决定左边距！ #}
                    <div>
                        {% if comment.user_img %}
                            <img src="{{ comment.user_img }}" alt="user_image" />      {# 如果用户有头像 #}
                        {% else %}
                            <img src="{% static 'blog/images/admin_image.jpg' %}" />      {# 如果用户没有头像 #}
                        {% endif %}
                    </div>
                    <div class="col-md-11 comment-content" style="margin-bottom: 10px;">
                        <strong>{{ comment.comment_title }}</strong>         {# 评论的title #}
                        <div>
                            {% if comment.parent_comment %}        {# 如果有父评论 #}
                                        {{ comment.user_name }}{{ request.user }}
                                        <i class="glyphicon glyphicon-share-alt"></i>
                                        {{ comment.parent_comment.user_name }}{{ request.user }}
                            {% else %}
                                    By&nbsp;&nbsp;
                                        {{ comment.user_name }}{{ request.user }}
                                    &nbsp;&nbsp;&nbsp;On&nbsp;&nbsp;
                            {% endif %}
                            <em>{{ comment.submit_date }}</em>
                            {% if request.session.login or request.user.is_authenticated %}
                            &nbsp;&nbsp;&nbsp;<a href="{% url 'blog:comment_reply' comment.id %}">回复</a>
                            {% endif %}
                        </div>
                    <br />
                        <p>{{ comment.comment }}</p>
                    </div>
                </div>
            {% endfor %}
            </div>
            </div>










                </div>
            <div class="col-md-3">
                {% block toc %}
                    <div class="row">
                        <div class="widget">
                            <h3>博客目录：</h3>
                                {{ entry.toc|safe }}
                        </div>
                    </div>
                {% endblock %}
                {% include 'blog/right_side_bar.html' %}
            </div>
        </div>
    </div>>


{% endblock %}

blog/templates/blog/right_side_bar.html
{% load blog_tags %}
    {% block toc %}{% endblock %}
    <div class="row">
    <div class="widget">
        <h3>最新博客：</h3>
        {% get_recent_entries as recent_entry_list %}
        {% for entry in recent_entry_list %}
            <div>
                <a href="{{ entry.get_absolute_url }}">{{ entry.title }}</a>作者：{{ entry.author }}
                <div>
                    发表于：{{ entry.created_time|date:'Y年m月d日' }}
                </div>
            </div>
        {% endfor %}
    </div>
    </div>

    <hr/>
    <div class="row">
    <div class="widget">
        <h3>推荐阅读：</h3>
        {% get_popular_entries as popular_entry_list %}
        {% for entry in popular_entry_list %}
            <div>
                <a href="{{ entry.get_absolute_url }}">{{ entry.title }}</a>
                <span class="badge" style="color: white;background-color: darkred">阅读量：{{ entry.visiting }}</span>
                {# 改变原本bootstrap 的颜色 可以直接改style#}
                <div>

                    作者：{{ entry.author }}发表于：{{ entry.created_time|date:'Y年m月d日' }}
                </div>
            </div>
        {% endfor %}
    </div>
    </div>

    <hr/>
    <div class="row">
    <div class="widget">
        <h3>分类：</h3>
        {% get_categories as category_list %}
            <ul class="list-group">
                {% for category in category_list %}
            <li class="list-group-item">
                <a href="{% url 'blog:blog_category' category.id %}">{{ category.name }}</a>
                <span class="badge">{% get_entry_count_of_category category.name%}</span>
            </li>
            </ul>
        {% endfor %}
    </div>
    </div>

    <hr/>
    <div class="row">
    <div class="widget">
        <h3>归档：</h3>
        {% archives as date_list %}
            <ul class="list-group">
                {% for date in date_list %}
            <li class="list-group-item">
                <a href="{% url 'blog:blog_archives' date.year date.month %}">
                <i class="glyphicon glyphicon-chevron-right"></i>
                {{ date.year }}年{{ date.month }}月
                <span class="badge">{% get_entry_count_of_date date.year date.month %}</span>
                    </a>
            </li>
            </ul>
        {% endfor %}
    </div>
    </div>


    <hr/>
    <div class="row">
    <div class="widget">
        <h3>标签云：</h3>
        {% get_tags as tag_list %}
                {% for tag in tag_list %}
                <a href="{% url 'blog:blog_tag' tag.id %}">
                    <span class="label {% cycle 'label-default' 'label-primary' 'label-success' 'label-info' 'label-warning' 'label-danger' %}">{{ tag.name }}</span>
                </a>
                 {% endfor %}
    </div>
    </div>

    <hr/>
    <div class="row">
        <div class="rss">
            <a href="/latest/feed"><i class="glyphicon  glyphicon-globe">RSS 订阅</i></a>
        </div>
    </div>